### ISSUE TITLE
Error when attempting to start the server

### ISSUE THREAD

**Issue by HamsterRICK** [EvanMulawski/BeamMP-EnvSync#8]
Hi there,

I've been trying to use this mod on my BeamMP Server, however I seem to get this error message in the server console every time I start the server:
`[22/1/2022 13:17:41] Main [WARN] main.lua | Resources/Server\BeamMP-EnvSync\main.lua:274: attempt to index a nil value (global 'MP')`
This seems to stop the LUA from running, as when I log on to the server as a client, the time is not set to what I want it to be from the config file and when I try to issue a '/env set time 3:00' command it does nothing.

**Comment by EvanMulawski** [comment]
Make sure you are running [BeamMP Server v3.0.0](https://github.com/BeamMP/BeamMP-Server/releases/tag/v3.0.0). If you can't update the server, I can provide instructions to install an older version.

**Comment by HamsterRICK** [comment]
I updated the server to V3.0.0 and the old error went away. However a new Lua Error now comes up:
`[22/01/22 20:55:25.715] ResultCheckThread [LUA ERROR] envSyncTick: [string "Resources\Server\BeamMP-EnvSync\main.lua"]:126: attempt to compare number with string`
I tried loading into the client but the time was not in sync.

**Comment by EvanMulawski** [comment]
Can you post the contents of your `envsync.config.lua` file?

**Comment by HamsterRICK** [comment]
`options = {}
options.admins = {}
options.timeOfDay = {}

--[[
    TIME OF DAY OPTIONS
--]]

-- The length of an in-game day in real-world seconds. Note: The in-game time scales affect the actual real-world length of the day.
options.timeOfDay.dayLengthRealTimeSeconds = 600

-- The game clock time the server should start with (equivalent to the in-game time slider time, "12:00" is noon and "00:00" is midnight).
options.timeOfDay.serverWorldStartTime = "0:00"

-- The factor at which the day progresses during the daytime.
options.timeOfDay.daytimeScale = 1

-- The factor at which the day progresses during the nighttime.
options.timeOfDay.nighttimeScale = 2

-- The horizontal location of the sun in the sky (in degrees). This currently has no effect.
options.timeOfDay.azimuth = 0

-- If false, this will "play" the time settings ("run the clock"). If true, the server will always sync the time it started with (the time will not change).
options.timeOfDay.fixed = false

--[[
    GENERAL OPTIONS
--]]

-- Approximate number of times per minute the server should send the current environment data to all clients. For example, a syncRate of 2 would sync the time of day with clients approximately every 30 seconds (2 syncs per minute).
options.syncRate = 30

-- Determines if debug logging is enabled.
options.debug = true

--[[
    PERMISSIONS
--]]

-- A table of user ID's that will be able to use chat commands to control this plugin. Only the key is used; the value can be anything (e.g. the player name).
-- options.admins.beammp_189094 = "Hornnnet"

return options
`

**Comment by EvanMulawski** [comment]
Change the following:

```lua
options.timeOfDay.serverWorldStartTime = "00:00"
```

**Comment by HamsterRICK** [comment]
Thanks you, the mod is now working.

**Comment by EvanMulawski** [comment]
You're welcome! Feel free to submit any bugs/requests/questions.

If you need to find your BeamMP user ID to configure admins, sign in to the BeamMP forum and then navigate to the following:

```
https://forum.beammp.com/u/<your_username>.json
```

There will be a `user_id` field in this response.
